[package]
name = "rust-tutrial"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "variable"
path = "src/variable.rs"

[[bin]]
name = "function"
path = "src/function.rs"

[[bin]]
name = "condition"
path = "src/condition.rs"

[[bin]]
name = "loop"
path = "src/loop.rs"